name = 'yassi'
license = 'MIT'
licenselink = 'https://github.com/yassi/hugo-theme-yassi/LICENSE'
description = 'Simple personal blog theme aimed at showcasing both projects and blog posts'
min_version = "0.133.1"

# The home page of the theme, where the source can be found
homepage = 'https://github.com/yassi/hugo-theme-yassi'

# If you have a running demo of the theme
demosite = 'https://yassi.dev'

# Taxonomy terms
tags = ['blog', 'personal', 'dark mode', 'portfolio', 'light', 'dark']
features = ['dark mode', 'carousels', 'social links']

# If the theme has a single author
[author]
  name = 'Yasser Toruno'
  homepage = 'yassi.dev'
